- name: Deploy Flask App
  hosts: flask
  become: true
  tasks:
    - name: Ensure pip and venv are installed
      apt:
        name:
          - python3-pip
          - python3-venv
        state: present
        update_cache: true

    - name: Create a virtual environment
      command: python3 -m venv /home/ubuntu/flaskenv
      args:
        creates: /home/ubuntu/flaskenv

    - name: Install Python requirements in venv
      command: /home/ubuntu/flaskenv/bin/pip install -r /home/ubuntu/flaskapp/requirements.txt
      environment:
        PATH: "/home/ubuntu/flaskenv/bin:{{ ansible_env.PATH }}"

    - name: Run the Flask app
      shell: |
        nohup /home/ubuntu/flaskenv/bin/python /home/ubuntu/flaskapp/app.py > /home/ubuntu/flaskapp/app.log 2>&1 &
      args:
        chdir: /home/ubuntu/flaskapp

